---
title: "System Dependencies"
author: "Tom Yu"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{System Dependencies}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
## System Dependencies

A dependency is a broad software engineering term used to refer when software relies on other software in order to be functional. For R package dependencies, the installation of the `synapser` package will take care of installing other R packages that `synapser` depends on, using dependencies specified in the [DESCRIPTION](../DESCRIPTION) file. However, lower level system dependencies are not automatically installed.

Most Windows and Mac machines have the required system dependencies. Linux machines, including most Amazon Web Services EC2 machines, will need to be configured before installing `synapser`.

### Required System Dependencies

* libssl-dev
* libcurl-dev
* libffi-dev
* zlib-dev

### Ubuntu Installation

To install these system dependencies on Ubuntu machines:
```
apt-get update -y
apt-get install -y dpkg-dev zlib1g-dev libssl-dev libffi-dev
apt-get install -y curl libcurl4-openssl-dev
```

Another option is to use the provided [Dockerfile](https://github.com/Sage-Bionetworks/synapser/blob/master/Dockerfile).
For more information on installing `synapser` with Docker, please see our [Docker vignettes](docker.html).

### Redhat Installation

To install these system dependencies on Redhat machines:
```
yum update -y
yum install -y openssl-devel curl-devel libffi-devel zlib-devel
yum install -y R
```
