library(PythonEmbedInR)

# create the autogenerated files
# srcRootDir is the root directory for the code base (i.e., prior to installation)
# the target dir is <srcRootDir>/man
autoGenerateRdFiles<-function(srcRootDir) {
	if (!file.exists(srcRootDir)) {
		stop(sprintf("%s does not exist.", srcRootDir))
	}

	functionInfo<-.getSynapseFunctionInfo(file.path(srcRootDir, "inst"))
	for(f in functionInfo) { 
		name<-f$synName
		args<-f$args
		doc<-f$doc
		tryCatch({
				content<-createRdContent(srcRootDir=srcRootDir,
						alias=name,
						title=name,
						description="",
						usage=usage(name, args),
						argument = formatArgs(args),
						details=doc
				)
				writeContent(content, name, srcRootDir)
					
			}, 
			error=function(e){
				cat(sprintf("Error generating doc for %s: %s\n", name, e[[1]]))
			}
		)
	}
}

usage<-function(name, args) {
	result<-NULL
	argNames<-args$args
	if (length(argNames)>0 && argNames[1]!='self') stop(sprintf("Expected 'self' but found %s", argNames[1]))
	keywords<-args$keywords
	varargs<-args$varargs
	defaults<-args$defaults
	result<-NULL
	if (length(argNames)>0) {
		for (i in 2:length(argNames)) {
			argName<-argNames[i]
			defaultIndex<- i+length(defaults)-length(argNames)
			if (defaultIndex>0) {
				result<-append(result, sprintf("%s=%s",argName, defaults[defaultIndex]))
			} else {
				result<-append(result, sprintf("%s", argName))
			}
		}
	}
	if (!is.null(keywords) || !is.null(varargs)) result<-append(result, "...")
	sprintf("%s(%s)", name, paste(result, collapse=", "))
}

formatArgs<-function(args) {
	argNames<-args$args
	if (length(argNames)>0 && argNames[1]!='self') stop(sprintf("Expected 'self' but found %s", argNames[1]))
	keywords<-args$keywords
	varargs<-args$varargs
	defaults<-args$defaults
	result<-NULL
	if (length(argNames)>0) {
		for (i in 2:length(argNames)) {
			argName<-argNames[i]
			defaultIndex<- i+length(defaults)-length(argNames)
			if (defaultIndex>0) {
				result<-append(result, sprintf("\\item{%s=%s}{}",argName, defaults[defaultIndex]))
			} else {
				result<-append(result, sprintf("\\item{%s}{}", argName))
			}
		}
	}
	if (!is.null(keywords) || !is.null(varargs)) result<-append(result, "\\item{...}{Extra parameters, passed by argument name.}")
	paste(lapply(X=args[[1]], function(x){sprintf("\\item{%s}{}",x)}), collapse=", ")
	paste(result, collapse="\n")
}

# doc has 
#:param xyz:
# :returns:
# TODO other formatting
processDetails<-function(raw) {
	# this replaces ':param <param name>:' with '<param name>:'
	result<-gsub(":param ([[:alnum:]]+):", "\\1:", raw)
	result<-gsub(":returns:", "returns:", result)
}

getReturned<-function(raw) {
	NULL
}

createRdContent<-function(srcRootDir, alias, title, description, usage, argument, details) {
	templateFile<-sprintf("%s/tools/rdTemplate.Rd", srcRootDir)
	connection<-file(templateFile, open="r")
	template<-paste(readLines(connection), collapse="\n")
	close(connection)
	
	content<-template
	if (!missing(alias) && !is.null(alias)) content<-gsub("##alias##", alias, content, fixed=TRUE)
	if (!missing(title) && !is.null(title)) content<-gsub("##title##", title, content, fixed=TRUE)
	if (!missing(description) && !is.null(description)) content<-gsub("##description##", description, content, fixed=TRUE)
	if (!missing(usage) && !is.null(usage)) content<-gsub("##usage##", usage, content, fixed=TRUE)
	if (!missing(argument) && !is.null(argument)) content<-gsub("##arguments##", argument, content, fixed=TRUE)
	returned<-NULL
	if (!missing(details) && !is.null(details)) {
		processedDetails<-processDetails(details)
		content<-gsub("##details##", processedDetails, content, fixed=TRUE)
		returned<-getReturned(details)
	}
	if (is.null(returned)) {
		content<-gsub("##value##", "", content, fixed=TRUE)
	} else {
		content<-gsub("##value##", "\value{\n"+returned+"\n}\n", content, fixed=TRUE)
	}
	content
}


writeContent<-function(content, className, srcRootDir) {
	fileName<-sprintf("%s/man/%s.Rd", srcRootDir, className)
	connection<-file(fileName, open="w")
	writeChar(content, connection, eos=NULL)
	writeChar("\n", connection, eos=NULL)
	close(connection)
	# cat(sprintf("Finished writing %s\n", fileName))
}

# now call autoGenerateRdFiles
args <- commandArgs(TRUE)
srcRootDir<-args[1]
# 'source' some functions shared with the synapse client package
source(sprintf("%s/R/shared.R",srcRootDir))
autoGenerateRdFiles(srcRootDir)

