# Define constructors and accessors for autogenerated classes
# 
# Author: brucehoff
###############################################################################

s4ClassesToAutoGenerate<-read.table(
  system.file("resources/s4ClassesToGenerate.txt",package="synapse"), 
  header=TRUE, colClasses=c("character", "character", "logical"))

for(i in 1:(dim(s4ClassesToAutoGenerate)[1])) { 
  className<-s4ClassesToAutoGenerate[i,"className"]
  schemaName<-s4ClassesToAutoGenerate[i,"schemaName"]
  if (!isVirtual(readEntityDef(schemaName, getSchemaPath()))) {
    defineS4ConstructorAndAccessors(className)
  }
}